services:

  influxdb3:
    image: influxdb:3-core
    container_name: influxdb3
    command: >
      influxdb3 serve
      --node-id node1
      --object-store file
      --data-dir /var/lib/influxdb3
    ports:
      - "8181:8181"
    volumes:
      - influxdb3-data:/var/lib/influxdb3
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  telegraf:
    image: telegraf
    container_name: telegraf
    depends_on:
      - influxdb3
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_DB=${INFLUX_DB}
      - INFLUX_URL=${INFLUX_URL}

  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - "8086:8086"
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: strongpassword
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket

volumes:
  influxdb3-data:
  grafana-data:
  influxdb2-data:
  influxdb2-config: